In [1]:
import csv
import numpy as np

In [2]:
numpy_arr = np.genfromtxt("dataset.csv", delimiter=",")

In [3]:
numpy_arr

array([[  0.  ,   0.  ,   2.  , ...,   3.  ,   2.67,   1.67],
       [  1.  ,   0.  ,   4.  , ...,   2.  ,   2.33,  -0.33],
       [  2.  ,   0.  ,   3.  , ...,   4.  ,   4.  ,   2.33],
       ...,
       [196.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [197.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [198.  ,   2.  ,    nan, ...,    nan,    nan,    nan]])

In [11]:
a = numpy_arr[2:4, :5]
print(a.shape)
print(a)

(2, 5)
[[2. 0. 3. 0. 2.]
 [3. 0. 2. 0. 2.]]


In [12]:
b = numpy_arr[5:7, 5:10]
print(b.shape)
print(b)

(2, 5)
[[1.33 5.   3.   4.   4.  ]
 [2.33 3.   2.   2.   2.33]]


In [13]:
a + b

array([[3.33, 5.  , 6.  , 4.  , 6.  ],
       [5.33, 3.  , 4.  , 2.  , 4.33]])

In [16]:
c = numpy_arr[8:10,2].reshape(2,1)
print(c.shape)
print(c)

(2, 1)
[[2.]
 [3.]]


In [17]:
c + a

array([[4., 2., 5., 2., 4.],
       [6., 3., 5., 3., 5.]])

In [19]:
d = numpy_arr[3:6, 5:10]
print(d.shape)
print(d)

(3, 5)
[[1.33 5.   4.   5.   4.67]
 [2.33 4.   4.   5.   4.33]
 [1.33 5.   3.   4.   4.  ]]


In [22]:
d.sum()

56.989999999999995

In [23]:
np.cos(d)

array([[ 0.23847605,  0.28366219, -0.65364362,  0.28366219, -0.04237629],
       [-0.68834402, -0.65364362, -0.65364362,  0.28366219, -0.37313797],
       [ 0.23847605,  0.28366219, -0.9899925 , -0.65364362, -0.65364362]])

In [21]:
np.isnan(numpy_arr)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False,  True, ...,  True,  True,  True],
       [False, False,  True, ...,  True,  True,  True],
       [False, False,  True, ...,  True,  True,  True]])

In [24]:
e = numpy_arr[:, 2:8]

In [25]:
e

array([[2.  , 0.  , 1.  , 1.  , 2.  , 3.  ],
       [4.  , 0.  , 4.  , 2.67, 3.  , 2.  ],
       [3.  , 0.  , 2.  , 1.67, 4.  , 4.  ],
       ...,
       [ nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan,  nan]])

In [26]:
e.sum()

nan

In [49]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])
arr_1, arr_2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [44]:
np.dot(arr_1, arr_2)

array([[19, 22],
       [43, 50]])

In [45]:
np.inner(arr_1, arr_2)

array([[17, 23],
       [39, 53]])

In [46]:
np.outer(arr_1, arr_2)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

In [48]:
# calculate the determinant of a square matrix
np.linalg.det(arr_1)

-2.0000000000000004

In [50]:
# solve a system of linear equations
A = np.array([[2, 4], [7, 8]])
b = np.array([19, 34])

In [51]:
# the equations are 2x + 4y = 19 and 7x + 8y = 34
np.linalg.solve(A, b)

array([-1.33333333,  5.41666667])

In [53]:
# inverse of a square matrix
arr1_inv = np.linalg.inv(arr_1)
arr1_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [54]:
# compute the sum of the diagonal elements of a matrix
np.trace(arr_1)

5