In [4]:
import csv
import numpy as np

### Slicing NumPy Arrays

In [5]:
with open('dataset.csv', newline='') as f:
    reader = csv.reader(f)
    data = list(reader)
print(data)

[['0', '0.0', '2', '0', '1', '1.0', '2', '3', '3', '2.67', '1.67'], ['1', '0.0', '4', '0', '4', '2.67', '3', '2', '2', '2.33', '-0.33'], ['2', '0.0', '3', '0', '2', '1.67', '4', '4', '4', '4.0', '2.33'], ['3', '0.0', '2', '0', '2', '1.33', '5', '4', '5', '4.67', '3.33'], ['4', '0.0', '3', '1', '3', '2.33', '4', '4', '5', '4.33', '2.0'], ['5', '0.0', '2', '0', '2', '1.33', '5', '3', '4', '4.0', '2.67'], ['6', '0.0', '3', '1', '3', '2.33', '3', '2', '2', '2.33', '0.0'], ['7', '0.0', '4', '0', '1', '1.67', '5', '2', '3', '3.33', '1.67'], ['8', '0.0', '2', '0', '2', '1.33', '3', '3', '3', '3.0', '1.67'], ['9', '0.0', '3', '0', '3', '2.0', '3', '4', '5', '4.0', '2.0'], ['10', '0.0', '3', '0', '1', '1.33', '4', '4', '5', '4.33', '3.0'], ['11', '0.0', '2', '0', '1', '1.0', '4', '2', '2', '2.67', '1.67'], ['12', '0.0', '3', '0', '2', '1.67', '3', '3', '4', '3.33', '1.67'], ['13', '0.0', '2', '0', '2', '1.33', '2', '1', '3', '2.0', '0.67'], ['14', '0.0', '1', '0', '2', '1.0', '3', '2', '2', '2.

In [6]:
numpy_arr = np.array(data)

In [7]:
numpy_arr[1,2]

'4'

In [9]:
# get one column
numpy_arr[:,1]

array(['0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '0.0',
       '0.0', '0.0', '0.0', '0.0', '0.0', '0.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0', '1.0',
       '1.0', '1.0',

In [10]:
numpy_arr[1, :]

array(['1', '0.0', '4', '0', '4', '2.67', '3', '2', '2', '2.33', '-0.33'],
      dtype='<U5')

In [11]:
slice = numpy_arr[2]

In [12]:
slice

array(['2', '0.0', '3', '0', '2', '1.67', '4', '4', '4', '4.0', '2.33'],
      dtype='<U5')

In [13]:
numpy_arr[2]

array(['2', '0.0', '3', '0', '2', '1.67', '4', '4', '4', '4.0', '2.33'],
      dtype='<U5')

In [14]:
slice[3] = 1000

In [15]:
slice

array(['2', '0.0', '3', '1000', '2', '1.67', '4', '4', '4', '4.0', '2.33'],
      dtype='<U5')

In [16]:
numpy_arr[2]

array(['2', '0.0', '3', '1000', '2', '1.67', '4', '4', '4', '4.0', '2.33'],
      dtype='<U5')

In [17]:
# partial slicing
numpy_arr[1, 1:6]

array(['0.0', '4', '0', '4', '2.67'], dtype='<U5')

In [22]:
numpy_arr[100:103,5:]

array([['2.33', '1', '5', '3', '3.0', '0.67'],
       ['1.67', '2', '3', '2', '2.33', '0.67'],
       ['2.33', '1', '5', '3', '3.0', '0.67']], dtype='<U5')

In [26]:
numpy_arr[105:-1, 2:3]

array([[''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       [''],
       ['3'],
       ['4'],
       ['2'],
       ['2'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['1'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['2'],
       ['2'],
       ['3'],
       ['4'],
       ['4'],
       ['2'],
       ['5'],
       ['4'],
       ['3'],
       ['2'],
       ['3'],
       ['4'],
       ['4'],
       ['3'],
       ['4'],
       ['2'],
       ['3'],
       ['3'],
       ['2'],
       ['3'],
       ['4'],
       ['4'],
       ['3'],
       ['2'],
       ['4'],
       ['2'],
       ['3'],
       ['1'],
       ['3'],
       ['3'],
       ['3'],
   

In [28]:
numpy_arr[105:-1:5, 2:3]

array([[''],
       [''],
       [''],
       [''],
       [''],
       ['3'],
       ['3'],
       ['3'],
       ['3'],
       ['4'],
       ['3'],
       ['3'],
       ['2'],
       ['2'],
       ['3'],
       ['1'],
       [''],
       [''],
       ['']], dtype='<U5')

In [31]:
numpy_arr[2:25:3,:]

array([['2', '0.0', '3', '1000', '2', '1.67', '4', '4', '4', '4.0',
        '2.33'],
       ['5', '0.0', '2', '0', '2', '1.33', '5', '3', '4', '4.0', '2.67'],
       ['8', '0.0', '2', '0', '2', '1.33', '3', '3', '3', '3.0', '1.67'],
       ['11', '0.0', '2', '0', '1', '1.0', '4', '2', '2', '2.67', '1.67'],
       ['14', '0.0', '1', '0', '2', '1.0', '3', '2', '2', '2.33', '1.33'],
       ['17', '0.0', '2', '0', '1', '1.0', '4', '2', '3', '3.0', '2.0'],
       ['20', '0.0', '4', '1', '1', '2.0', '4', '4', '4', '4.0', '2.0'],
       ['23', '0.0', '4', '0', '2', '2.0', '4', '1', '5', '3.33', '1.33']],
      dtype='<U5')

In [32]:
numpy_arr[1:8:2,:]

array([['1', '0.0', '4', '0', '4', '2.67', '3', '2', '2', '2.33',
        '-0.33'],
       ['3', '0.0', '2', '0', '2', '1.33', '5', '4', '5', '4.67', '3.33'],
       ['5', '0.0', '2', '0', '2', '1.33', '5', '3', '4', '4.0', '2.67'],
       ['7', '0.0', '4', '0', '1', '1.67', '5', '2', '3', '3.33', '1.67']],
      dtype='<U5')

### Indexing, Filtering, and Broadcasting NumPy Arrays

In [33]:
numpy_dataset = np.genfromtxt('dataset.csv', delimiter=',')

In [34]:
numpy_dataset

array([[  0.  ,   0.  ,   2.  , ...,   3.  ,   2.67,   1.67],
       [  1.  ,   0.  ,   4.  , ...,   2.  ,   2.33,  -0.33],
       [  2.  ,   0.  ,   3.  , ...,   4.  ,   4.  ,   2.33],
       ...,
       [196.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [197.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [198.  ,   2.  ,    nan, ...,    nan,    nan,    nan]])

In [35]:
numpy_dataset[3, 4]

2.0

In [36]:
indexer_tuple = (3,4)

In [37]:
numpy_dataset[indexer_tuple]

2.0

advanced indexing using mutable data structures

In [38]:
indexer_arr = [3, 4]

In [39]:
numpy_dataset[indexer_arr]

array([[3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33],
       [4.  , 0.  , 3.  , 1.  , 3.  , 2.33, 4.  , 4.  , 5.  , 4.33, 2.  ]])

masking

In [40]:
small_arr = numpy_dataset[:3, :3]

In [45]:
small_arr

array([[0., 0., 2.],
       [1., 0., 4.],
       [2., 0., 3.]])

In [46]:
# mask to find values that are greater than 2
mask = np.where(small_arr > 2)

In [47]:
mask

(array([1, 2]), array([2, 2]))

In [48]:
small_arr[mask]

array([4., 3.])

Broadcasting

In [49]:
np.array(range(6))

array([0, 1, 2, 3, 4, 5])

In [50]:
np.array(6) * np.array(range(6))

array([ 0,  6, 12, 18, 24, 30])

In [51]:
2 + np.zeros(5)

array([2., 2., 2., 2., 2.])

In [55]:
a = np.arange(5).reshape(1,5)
a

array([[0, 1, 2, 3, 4]])

In [59]:
b = np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
a * b

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76],
       [ 0, 21, 44, 69, 96]])