In [10]:
import numpy as np

In [11]:
a = np.array([[12, 15], [10, 1]])

In [12]:
a

array([[12, 15],
       [10,  1]])

In [13]:
np.sort(a, axis=0)

array([[10,  1],
       [12, 15]])

In [14]:
np.sort(a, axis=-1)

array([[12, 15],
       [ 1, 10]])

In [15]:
np.sort(a, axis=None)

array([ 1, 10, 12, 15])

In [20]:
k = np.array([2, 4, 34, 5, 6, 7, 9, 24])

In [21]:
b = np.argsort(k)

In [22]:
c = np.zeros(len(b), dtype=int)

In [23]:
c

array([0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
for i in range(0, len(b)):
    c[i] = k[b[i]]

In [25]:
k

array([ 2,  4, 34,  5,  6,  7,  9, 24])

In [26]:
c

array([ 2,  4,  5,  6,  7,  9, 24, 34])